# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  cucumber-test:
   name: Run on Chrome
   runs-on: ubuntu-latest
   container: docker pull selenium/node-chrome:latest  
   steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
   
      - name: Grant Execution Permission For WebDriver
        run: chmod +x webdriver
    
      - name: Clean Maven Project
        run: mvn clean
    
      - name: Compile Maven Project
        run: mvn compile
    
      - name: Run Maven Project
        run: mvn verify
